### ISSUE TITLE
无法编译通过

### ISSUE THREAD

**Issue by likongzun** [yss930819/AR.DroneMultiControl#1]
你好，请问这个项目需要用哪个版本vs？
我用2010,2012,2013都无法编译AR.Drone.Vicon
是否需要特殊设置，请指教，谢谢！

**Comment by yss930819** [comment]
项目使用Vs2012编译
要设置AR.Drone.Vicon项目不使用预编译头文件才能编译通过。
单机点到点控制需要有室内定位系统Vicon

**Comment by likongzun** [comment]
谢谢回复，我在用另外一套定位系统，基于UWB的，我是要参考其他代码，vicon部分基本用不到
vicon好像是基于光学的？精度如何呢？

**Comment by yss930819** [comment]
Vicon是光学的，捕捉精度很高 静态精度毫米级。

**Comment by likongzun** [comment]
这个精度很吸引人啊，但是AR本身的漂移会造成较大误差，Vicon的高精度就显示不出来了吧。
另外，能给个Vicon的连接吗？我也了解一下。

**Comment by yss930819** [comment]
Vicon 我这里只有客户端内容，在Vicon项目里有源文件。其他部分是师兄做的无法提供

**Comment by likongzun** [comment]
我想看Vicon设备的介绍，不是想看源文件:-)
另外，这套设备精度这么高，范围多大？一套设备得多少钱呢？
我一直在找一套可以大范围（几百米）内高精度（不要求毫米，几厘米就可以）的定位设备，当然是越便宜越好。不知道你有没有研究过？有没有推荐或者建议？

**Comment by yss930819** [comment]
我这里没有设备介绍，因为那不是我的毕设内容。
我毕设做完也就再也不用这个了，没研究过这方面的内容

**Comment by likongzun** [comment]
好吧，谢谢
